### ISSUE TITLE
Integrate WattDepot

### ISSUE THREAD

**Issue by bretkikehara** [bretkikehara/wattdepot-visualization#2]
Integrate mock WattDepot senoss so that the animation may pull data from those sensors.

**Comment by anthonyxu72** [comment]
Example code to connect to a WattDepot server in the test branch at org.wattdepot.visualization.wattdepot.connectWattDepot.java.A skeleton of an example WattDepot server with resources of a few UH Manoa buildings are location in src/main/resources/.wattdepot.zip of the test branch. Unzip into root folder. Download WattDepot and run the jar file. The sensors are not implemented.
